### ISSUE TITLE
custom build path

### ISSUE THREAD

**Issue by mfhholmes** [101loops/grunt-go#4]
my project layout looks like this

project
|--Gruntfile.js
|--exec1
|--exec2
|--go_code_for_exec1_folder
|--|--main.go
|--go_code_for_exec2_folder
|--|--main.go

There's a task option for specifying the root of each grunt-go task, but it seems to concatenate with the GOROOT rather than specifying the input parameter on the "go build command".

So my task looks like:
        go:{
            options:{
                GOPATH:["/home/marcus/Dev/Go"]
            },
            exec1:{
                output:"exec1",
                root:"go_code_for_exec1_folder"
            }
            exec2:{
                output:"exec2",
                root:"go_code_for_exec2_folder"
            }
        }

what I want is Grunt to run:
go build -o exec1 ./go_code_for_exec1_folder
go build -o exec2 ./go_code_for_exec2_folder

what I get is Go complaining because it can't find dependency libs in: "/home/marcus/Dev/Go/src/github.com/mfhholmes/myproject/home/marcus/Dev/Go/src/github.com/libauthor/lib" (reasonably enough) - it seems to be concatenating the root onto the path instead of as a build param.

not sure if I'm misunderstanding something. I had a look through your source but didn't really grok the use of the root option from it.

Otherwise top job, well done. If I had a normal project structure this would work perfectly first time ;)

**Comment by mwmahlberg** [comment]
Since it is severely buggy, it'd be nice if you took it of from the npm repo. Not to be able to use absolute paths for GOPATH renders it literally useless.

**Comment by stephanos** [comment]
@mfhholmes I didn't really pay attention to this repository. My bad. If you'd review the PR https://github.com/101loops/grunt-go/pull/8 I could merge it and release a new version if that would help you.

PS: I think you can't remove stuff from npm anymore after the recent leftpad incident

**Comment by mwmahlberg** [comment]
@stephanos lgtm, fwiw. The travis issue seems to be related to a dependency which seems not to be installable in node-0.8, from what I can see.
